### ISSUE TITLE
Flujo de juego

### ISSUE THREAD

**Issue by dragoxxkiller** [CIFP-Jose-luis-Garci/Umvra#12]
o Objetivo del jugador
o Flujo de juego: explica el transcurso de una partida, los pasos a seguir desde que el juego
arranca hasta completar un nivel completo.

**Comment by SergioGrandeH** [comment]
[Uploading Flujo de juego.docx…]()

**Comment by SergioGrandeH** [comment]
Pasandolo a 2D
