### ISSUE TITLE
- HISTORIA Y NARRATIVA:

### ISSUE THREAD

**Issue by dragoxxkiller** [CIFP-Jose-luis-Garci/Umvra#13]
- HISTORIA Y NARRATIVA:
o Lema
o Historia
o Plot points
o Narrativa: indicar qué tipo de narrativa o narrativas se adaptan más a la historia de
vuestro juego y por qué, qué aporta al jugador, qué ventajas e inconvenientes tiene…
(tema 4)

**Comment by Javierkun99** [comment]
[Historia y narrativa.odt](https://github.com/CIFP-Jose-luis-Garci/Umvra/files/7522326/Historia.y.narrativa.odt)

Adjunto archivo

**Comment by Javierkun99** [comment]
Cierro el issue
