### ISSUE TITLE
Dinámicas y mecánicas

### ISSUE THREAD

**Issue by dragoxxkiller** [CIFP-Jose-luis-Garci/Umvra#14]
- DINÁMICAS Y MECÁNICAS: aplicando los conceptos incluidos en el tema 4
- MOVIMIENTOS Y FÍSICAS
o Controles: durante el juego (si el jugador puede utilizar gamepad y teclado, indicar los
controles de ambos dispositivos) y en la navegación por lo menús
o Interacción entre elementos (tenéis un ejemplo en la página 10 de la GDD Sion)

**Comment by alhgo** [comment]
Añadido a mi proyecto. Recordad: las mecánicas van a estar determinadas por las animaciones con las que contamos (para eso necesitamos un modelo al que animar)

**Comment by GenuinoXX** [comment]
He terminado el coso
[Dinámicas, Mecánicas e Interfaz.docx](https://github.com/CIFP-Jose-luis-Garci/Umvra/files/7515390/Dinamicas.Mecanicas.e.Interfaz.docx)

**Comment by GenuinoXX** [comment]
He hecho ajustes en el documento
[Dinamicas.Mecanicas.e.Interfaz.docx](https://github.com/CIFP-Jose-luis-Garci/Umvra/files/7515505/Dinamicas.Mecanicas.e.Interfaz.docx)

**Comment by SergioGrandeH** [comment]
Rediseñando mecánicas, añadiendo mas armas/herramientas y cambiando las batallas de bosses

**Comment by GenuinoXX** [comment]
Aquí está el documento mejorado
[Dinamicas.Mecanicas.docx](https://github.com/CIFP-Jose-luis-Garci/Umvra/files/7749559/Dinamicas.Mecanicas.docx)
