### ISSUE TITLE
Estilo visual/concept art

### ISSUE THREAD

**Issue by dragoxxkiller** [CIFP-Jose-luis-Garci/Umvra#15]
- ESTILO VISUAL
o Concept art
o Diseño de personajes
o Diseño de escenarios
o Objetos, armas, power up, coleccionables…
o Otros: mapas, botones…

**Comment by dragoxxkiller** [comment]
Termina
[Uploading Estilo visual_ Concept-Art.docx…]()
do

**Comment by SergioGrandeH** [comment]
Pasándolo a 2D
