### ISSUE TITLE
Crear el enemigo con forma de líquidos

### ISSUE THREAD

**Issue by alhgo** [CIFP-Jose-luis-Garci/Umvra#16]
Algo muy importante en este juego (y que no parece nada fácil) es crear un personaje con forma "líquida". Por ello tenemos que realizar una profunda investigación para ver cómo podemos hacerlo. En principio veo tres posibilidades:

1. Usar simulación de líquidos dentro de un contenedor transparente. Esto me parece lo más difícil
2. Usar sistemas de partículas. Están pensados para explosiones, gases o fuego, pero quizás se pueda adaptar
3. Crear texturas animadas. Esta quizás sea la más asquible, pero hay que investigarlo.

En cualquier caso, yo partiría de un modelo 3D del personaje con el que poder realizar pruebas. hay que investigar.

**Comment by dragoxxkiller** [comment]
Ya no se necesita ya que sera 2D
