### ISSUE TITLE
Diagrama de Gantt

### ISSUE THREAD

**Issue by SergioGrandeH** [CIFP-Jose-luis-Garci/Umvra#18]

**Comment by dragoxxkiller** [comment]
[Tabla gantt - Hoja 1.pdf](https://github.com/CIFP-Jose-luis-Garci/Umvra/files/7722722/Tabla.gantt.-.Hoja.1.pdf)

**Comment by SergioGrandeH** [comment]
![gantt  GDD](https://user-images.githubusercontent.com/90465369/146266774-66d585bd-ac6d-42e5-820e-6c93629c29cb.jpg)
[Tabla.gantt.-.Hoja.1.pdf](https://github.com/CIFP-Jose-luis-Garci/Umvra/files/7722795/Tabla.gantt.-.Hoja.1.pdf)
