### ISSUE TITLE
Equipo humano y Flujo trabajo

### ISSUE THREAD

**Issue by dragoxxkiller** [CIFP-Jose-luis-Garci/Umvra#21]
Equipo humano necesario (departamentos, roles y número de personas necesarias si lo llevarais
a cabo realmente)
- Flujo de trabajo (workflow) que más se adecue al proyecto

**Comment by SergioGrandeH** [comment]
[PRESUPUESTO Y FINANCIACIÓN UMVRA.pdf](https://github.com/CIFP-Jose-luis-Garci/Umvra/files/7857217/PRESUPUESTO.Y.FINANCIACION.UMVRA.pdf)
