### ISSUE TITLE
Género

### ISSUE THREAD

**Issue by SergioGrandeH** [CIFP-Jose-luis-Garci/Umvra#3]
INTRODUCCIÓN
o Concepto del juego: en dos o tres líneas. Deberá responder a la pregunta ¿de qué va
vuestro videojuego?
o Características principales: un listado de los pilares fundamentales que tendrá el juego
ya sea en el aspecto de jugabilidad, mecánicas, narrativa…
- GÉNERO: género principal o combinación de géneros que tendrá el videojuego según lo visto en
el tema 2
- PLATAFORMA: consola, pc, aplicaciones móviles… Justificar por qué habéis elegido esa
plataforma (puedes apoyarte en los datos de AEVI)

**Comment by Javierkun99** [comment]
Se ha creado un documento hablando sobre las respectivas partes mencionas aquí. Es poco posible que haya que cambiar algo.

**Comment by vcalzadaga** [comment]
este es el texto definitivo

**Comment by vcalzadaga** [comment]
Falta añadir bla bla bla (ejemplo)

**Comment by Javierkun99** [comment]
[Género e historia.pdf](https://github.com/CIFP-Jose-luis-Garci/Umvra/files/7499599/Genero.e.historia.pdf)
Adjunto

**Comment by Javierkun99** [comment]
[Género e historia.pdf](https://github.com/CIFP-Jose-luis-Garci/Umvra/files/7504129/Genero.e.historia.pdf)

Adjunto documento corregido de "Género e historia"

**Comment by Javierkun99** [comment]
Con esto cierro el issue y así darlo por terminado

**Comment by Javierkun99** [comment]
[Género e historia (copia).odt](https://github.com/CIFP-Jose-luis-Garci/Umvra/files/7522362/Genero.e.historia.copia.odt)

Adjunto archivo definitivo

**Comment by Javierkun99** [comment]
Espero no hacer más cambios de este modo. Cierro issue
