### ISSUE TITLE
Diseño de personajes

### ISSUE THREAD

**Issue by SergioGrandeH** [CIFP-Jose-luis-Garci/Umvra#4]
- PERSONAJES:
o Personajes jugables: Historia, aspecto gráfico, características, habilidades
o NPC´s: Historia, aspecto gráfico, características, habilidades
o Enemigos: Historia, aspecto gráfico, características, habilidades

**Comment by dragoxxkiller** [comment]
Casi he terminado personajes me faltan 2 de ellos.
Voy a empezar Estilo visual también.

**Comment by dragoxxkiller** [comment]
Me falta el diseño grafico del espectro/fantasma lo pondré esta noche, mientras tanto subo el documento sin el para revisión
[Personajes (1).docx](https://github.com/CIFP-Jose-luis-Garci/Umvra/files/7520965/Personajes.1.docx)
