### ISSUE TITLE
Interfaz

### ISSUE THREAD

**Issue by SergioGrandeH** [CIFP-Jose-luis-Garci/Umvra#5]
- INTERFAZ
o Mapa de navegación: diagrama de bloques donde se muestre la navegación del
usuario durante el juego
o Menús
o HUD

**Comment by dragoxxkiller** [comment]
buscar las animaciones basicas, correr, saltar , agacharse... para la demo

**Comment by alhgo** [comment]
He añadido este issue a mi proyecto. Solo una cosa, no mezcléis temas en el issue. Si este es sobre Interfaz, cread otro sobre animaciones. Después de diseñar el diagrama de flujo queda diseñar cada menú, cada botón y cada elemento del HUD para incorporarlo al juego.

**Comment by GenuinoXX** [comment]
He acabado todo lo que necesitamos para la interfaz:
![Mapa_Navegacion](https://user-images.githubusercontent.com/79325966/141383360-c40ec4bb-282b-4a31-84e4-eff98020c4f2.jpg)
![Menu_Principal1](https://user-images.githubusercontent.com/79325966/141383381-97316227-84db-4071-90fc-fc5c0110c8ba.jpg)
![Menú_Opciones](https://user-images.githubusercontent.com/79325966/141383393-65e58346-ab3a-40f7-a065-7e83d5f45b3e.jpg)

![Menu_Inventario](https://user-images.githubusercontent.com/79325966/141383494-a73aa469-c2a5-4203-88de-d9e29e2305c1.jpg)
![Interfaz_Juego](https://user-images.githubusercontent.com/79325966/141383623-b2b5feaf-9904-4bbf-89f1-8d58bb630d5a.jpg)
