### ISSUE TITLE
Diseño de niveles

### ISSUE THREAD

**Issue by SergioGrandeH** [CIFP-Jose-luis-Garci/Umvra#6]
- DISEÑO DE NIVELES

o Niveles del juego: describir sus características principales, los enemigos u obstáculos
que encontrará el jugador, con especial incidencia en el nivel que tenéis pensado
desarrollar para la práctica final
o Dificultad: hablad de la progresión de la dificultad durante el juego. Os aconsejo
elaborar un diagrama similar al de la pag 14, tema 3
o Tutorial: cómo lo vais a integrar. Vais a utilizar texto o no. Influencias de otros títulos en
los que os habéis inspirado.

**Comment by dragoxxkiller** [comment]
diseño del primer nivel con los puzzles y acciones ya definidas (sergio te ayudo en esto)

**Comment by SergioGrandeH** [comment]
Subo la primera versión del diseño de niveles[

**Comment by SergioGrandeH** [comment]
[Flujo de juego.docx](https://github.com/CIFP-Jose-luis-Garci/Umvra/files/7515187/Flujo.de.juego.docx)

**Comment by SergioGrandeH** [comment]
Pasándolo a 2D y rediseñando el tutorial
