### ISSUE TITLE
Referencias e información

### ISSUE THREAD

**Issue by SergioGrandeH** [CIFP-Jose-luis-Garci/Umvra#7]
- REFERENTES: otras obras (videojuegos, libros, películas… ) que os han influido para diseñar el
juego. Por cada título que mencionéis, tenéis que indicar en qué aspectos concretos os habéis
inspirado
- ALCANCE (según vuestra previsión inicial, indicadme hasta dónde tenéis pensado desarrollar de
aquí al mes de marzo, si vais a modelar los personajes desde cero, en qué aspectos vais a utilizar
material de librerías…)
- PÚBLICO OBJETIVO (TARGET): cuando más específico sea, mejor. Relacionar con los datos
publicados en el anuario AEVI
- EQUIPO HUMANO
o Relación de los miembros del equipo con los perfiles profesionales vistos en el tema 3.
¿De qué os vais a encargar cada uno?
o Background del equipo. Un breve recorrido por la historia del equipo y sus
componentes. Se recomienda incluir alguna fotografía dentro del entorno de trabajo.
Por ejemplo: una reunión del equipo de trabajo, programando, diseñando bocetos para
el juego…

**Comment by Javierkun99** [comment]
Creé un documento hablando de estas partes, pero habrá cambios sobre los perfiles profesionales para mejorarlo un poco más

**Comment by dragoxxkiller** [comment]
simulacion de liquidos para el enemigo basico, para la demo
