### ISSUE TITLE
Música

### ISSUE THREAD

**Issue by SergioGrandeH** [CIFP-Jose-luis-Garci/Umvra#8]
MÚSICA Y EFECTOS: hablad del estilo sonoro que tendrá el juego y recopilar algunas músicas y
efectos representativos que tendrá el videojuego. Ejemplo: música menú, música nivel 1, efecto
ataque, efecto disparo…

**Comment by Javierkun99** [comment]
[Canciones (referencias).docx](https://github.com/CIFP-Jose-luis-Garci/Umvra/files/7522269/Canciones.referencias.docx)

Adjunto archivo

**Comment by Javierkun99** [comment]
Cierro esta issue

**Comment by Javierkun99** [comment]
Este último es el bueno. Cierro issue
